import {StyleSheet,Dimensions} from 'react-native';
module.exports = StyleSheet.create({
    header:{
        backgroundColor:"white",
        width:"100%",
        height:80,
        justifyContent:"space-between",
        alignItems:"center",
        marginHorizontal:10
    },
    logoimg:{
        marginRight:20,
        height:100,
        width:100,
        resizeMode:'contain',
    },
    title:{
        marginLeft:20,
        fontSize:20,
        fontWeight:"bold"
    },
    footer:{
       backgroundColor:'white',
       flexDirection:'row',
       paddingHorizontal:20,
    },
    selectlistbar:{
        height:50,
        backgroundColor:'white',
        flexDirection:'row',
        alignItems:"center",
        justifyContent:"space-between",
        borderWidth:1,
        borderColor:'#d3d3d3',
        paddingHorizontal:10
    },
    searchbar:{
        height:80,
        backgroundColor:'white',
        flexDirection:'row',
        alignItems:"center",
        justifyContent:"space-between",
        borderTopWidth:1,
        borderColor:'#d3d3d3',
        paddingHorizontal:10
    },
    searchbartext:{
        fontSize:16,
        color:'#656565'
    },
    paybutton:{
        backgroundColor:'#99242b',
        alignItems:"center",
        justifyContent:"center",
        height:50,
        width:100
    },
    paybuttontext:{
        fontSize:16,
        color:'white'
    },
    footerimg:{
        height:30,
        width:30,
        resizeMode:'contain',
        marginRight:10,
        top:10
    },
    footerimg2:{
        height:100,
        width:100,
        resizeMode:'contain',
        marginRight:10,
        bottom:50
    },
    checkboximg:{
        height:30,
        width:30,
        resizeMode:'contain',
        marginRight:10,
    },
    content:{
        backgroundColor:'grey',
        flex:1
    },
    //shopping
    shoppingarea:{
        flex:1,
        height:200,
        backgroundColor:'white',
        borderWidth:1,
        borderColor:'#d3d3d3',
        flexDirection:'row',
        justifyContent:"flex-start",
        alignItems:'center',
        paddingHorizontal:10
    },
    shoppingphotoimg:{
        height:100,
        width:100,
        resizeMode:'contain',
    },
    shoppingareadetail:{
        flexDirection:'column',
        alignItems:"flex-start",
        justifyContent:"center",
        flex:1,
        backgroundColor:"white",
        marginLeft:20,
        bottom:10
    },
    shoppingareadetailrow:{
        flexDirection:"row",
        justifyContent:"space-between",
        //alignItems:"center",
    },
    shoppingareadetailtext:{
        fontSize:16,
        color:"#99242b",
        marginVertical:0
    },
    shoppingareadetailtext2:{
        fontSize:20,
        fontWeight:"bold",
        color:"#99242b",
        marginVertical:15
    },
    shoppingareadetailtext3:{
        fontSize:20,
        fontWeight:"bold",
        color:"#99242b",
        marginVertical:15,
        left:50
    },
    //discovery
    searchbarimg: {
        height:100,
        width:100,
        resizeMode:'contain',
        alignItems:"flex-end"
    },
    societyarea:{
        flex:1,
        height:120,
        backgroundColor:'white',
        borderWidth:1,
        borderColor:'#d3d3d3',
        flexDirection:'row',
        justifyContent:"flex-start",
        alignItems:'center',
        paddingHorizontal:10
    },
    eventarea:{
        marginTop:5,
        flex:1,
        height:150,
        backgroundColor:'white',
        alignItems:'center',
        justifyContent:"center",
        paddingHorizontal:10,
        resizeMode:'contain'
    },
    eventareatitle:{
        fontWeight:'bold',
        fontSize:25,
        color:'white'
    },
    eventareatext:{
        fontSize:18,
        color:'white'
    },
    //news
    featureeventarea:{
        flex:1,
        backgroundColor:"white",
        paddingHorizontal:0
    },
    featureeventareatext:{
        fontSize:18,
        marginTop:5,
        marginHorizontal:20
    },
    featureeventareaview:{
        marginVertical:10
    },
    eachfeatureeventarea:{
        height:200,
        width:150,
        marginHorizontal:5,
        resizeMode:'contain',
        borderRadius:30,
        overflow:'hidden',
        alignItems:"center",
        justifyContent:"center"
    },
    eachfeatureeventtext:{
        color:'white',
        fontSize:18
    },
    eachfeatureeventtext2:{
        color:'white',
        fontSize:14
    },
    recenteventarea:{
        flex:1,
        backgroundColor:"white",
        paddingHorizontal:0
    },
    recenteventareatext:{
        fontSize:18,
        marginTop:5,
        marginHorizontal:20
    },
    eachrecenteventarea:{
        flex:1,
        height:150,
        resizeMode:'contain',
        alignItems:"center",
        justifyContent:"center"
    },
    eachrecenteventtext:{
        color:'white',
        fontSize:18,
        fontWeight:"bold"
    },
    eachrecenteventtext2:{
        color:'white',
        fontSize:14
    },
    eachrecenteventdetail:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginHorizontal: 20,
        height:100
    },
    addcartimg:{
        height:30,
        width:30,
        resizeMode:'contain',
    },
    //PersonalInfo
    personalinfored:{
        backgroundColor:"#99242b",
        height:100,
        alignItems:"center"
    },
    personaliconimg:{
        height:160,
        width:160,
        resizeMode:'contain',
        left:'31%',
        bottom:80,
    },
    personalinfowhite:{
        backgroundColor:"white",
        height:150,
        alignItems:"center",
        //flexWrap:'wrap',
        //justifyContent:'flex-start'
    },
    personinfotitle:{
        fontSize:25,
        fontWeight:'bold',
        bottom:50
    },
    personinfotext:{
        fontSize:18,
        //fontWeight:'bold',
        bottom:30,
        marginHorizontal:60
    },
    personinfotab:{
        height:50,
        width:150,
        //backgroundColor:'yellow',
        alignItems:"center",
        justifyContent:"center"
    },
    personinfotabactive:{
        height:50,
        width:150,
        //backgroundColor:'yellow',
        borderColor:"#99242b",
        borderBottomWidth:3,
        alignItems:"center",
        justifyContent:"center"
    },
    personinfotabtext:{
        fontSize:20,
        fontWeight:"bold"
    },
    personinfotabtextactive:{
        fontSize:20,
        fontWeight:"bold",
        color:'#99242b'
    },
    eachboxarea:{
        flex:1,
        height:120,
        alignItems:"center",
        justifyContent:"center"
    },
    boxtitle:{
        fontSize:20,
        fontWeight:"bold",
        color:"white"
    },
    boxtext:{
        fontSize:16,
        color:"white"
    }

});


